### ISSUE TITLE
question about GetActiveUniformBlockiv in OpenGL ES spec3.2

### ISSUE THREAD

**Issue by TimeToWakeUp** [KhronosGroup/OpenGL-API#73] opened 2020-08-01 10:05 UTC
Hi, I have a question about GetActiveUniformBlockiv api. In OpenGL ES spec3.2, the input parameter pname of GetActiveUniformBlockiv can be set to UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER, UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER and UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER, but why did I not find the values of the UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER, UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER, and UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER macros in the header file of the official khronos gles opegl api?
![image](https://user-images.githubusercontent.com/34735089/89099403-7a5ac600-d421-11ea-910f-48b470123e94.png)

This is the link to the spec document what I'm using, and you can see the three enumerants in this document.
https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf

**Comment by pdaniell-nv** [comment] 2020-08-04 20:13
Looks like this is a dupe of https://github.com/KhronosGroup/OpenGL-Registry/issues/417.

**Closed as completed by pdaniell-nv** 2020-08-04 20:13 UTC
